### ISSUE TITLE
[For tracking] Batch frames from stream reader.

### ISSUE THREAD

**Issue by The-Scout** [Amorano/Jovimetrix#10]
Talked about this on reddit, but you said you would implement a batch feature into the node, putting this here so you can remember. <3 hope you are doing well, and happy new years!!

**Comment by Amorano** [comment]
![image](https://github.com/Amorano/Jovimetrix/assets/225178/94bb5cc9-1bc3-45b1-9bf9-703e24205c29)

This should get you started in the right direction. Pushed in the latest.

If you change the BATCH to a value > 1 it will batch that number of frames based on the second number in BATCH (independent FPS for capture).

Let me know if that is the goal.

**Comment by The-Scout** [comment]
Going to take a look now!!

**Comment by The-Scout** [comment]
Works great, now to figure out how to stop controlnet from lagging and crashing with large batches.
