### ISSUE TITLE
Can not install ffmpeg-python

### ISSUE THREAD

**Issue by cjh1228** [Amorano/Jovimetrix#11]
Collecting future (from ffmpeg-python->-r requirements.txt (line 5))
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\chenyu\AppData\Local\Temp\pip-install-fczlsycb\future_a9bdc10971244508a59f8b8c30f36c38\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Amorano** [comment]
Using cached future-0.18.3.tar.gz (840 kB)  

Seems your cached version of the module required by ffmepg-python wont install. I guess you can try a forced update yourself, but this isnt really a problem with my library, but a problem with pip or your cached modules for python.

To force an update, using the python from your comfy version:

python.exe -m pip install future --force-reinstall

you can also do this for any other packages, forcing them fully with something like:

pip install -I <package>
pip install --ignore-installed <package>

HTH
