### ISSUE TITLE
Camera index out of range [ERROR:0@25.392] 

### ISSUE THREAD

**Issue by chalkncheese** [Amorano/Jovimetrix#13]
Hi since installing in Comfyui I'm receiving this error "[ERROR:0@25.392] global obsensor_uvc_stream_channel.cpp:156 cv::obsensor::getStreamChannelGroup Camera index out of range" it seems to be related to OpenCV and due to the fact that I am not using a laptop or do not have a webcam attached to my desktop (Windows 10) pc. I am using a virtual environment for my ComfyUI (venv is activated) and I have used pip install to install the requirements.txt included in your custom_node Jovimetrix folder which has downgraded opencv_python  to v.4.8.1.78. Which file do I need to change to solve the error? Thank you in advance.

**Comment by Amorano** [comment]
It is not an actual error. On startup, I search for any cameras so you can use them in the streamreader node. IIt will iterate all the cameras on system and "error" when it cant find anymore, even if there are none.

I added an env switch **JOV_SCAN_DEVICES** if you set that to 0 or false it will ignore the camera scan at startup.

Let me know if that helps to resolve the issue.
