### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Hangover3832** [Amorano/Jovimetrix#14]
Hi. I get this error when I select the USB camera in the Stream Reader, even though the camera get activated.

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\comfy\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfy\ComfyUI\custom_nodes\Jovimetrix\nodes\device.py", line 243, in run
    cc, w, h = channel_count(img)[:2]
    ^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

![grafik](https://github.com/Amorano/Jovimetrix/assets/116489681/5f790004-eb8c-4b0b-ac2a-654318d373c4)

**Comment by Hangover3832** [comment]
Wow. I can adjust ComfyUI parameters with my MIDI controller. That's convenient ;-).

**Comment by Amorano** [comment]
Thank you! That was a nasty typo I left in the core. Let me know if the latest is good.

**Comment by Hangover3832** [comment]
Yes it is, thank you!
