### ISSUE TITLE
Just a question :/

### ISSUE THREAD

**Issue by OtakuFra** [Amorano/Jovimetrix#15]
Hi, sorry for bothering you, but where am i supposed to set the gifski path exactly ? I din't understand what the "set JOV_GIFSKI='C:\gifski-1.14.4'" is meant to be. I've set the cli file of gifski on my path but your repo seems not to detect it. 
Sorry again and thank for your help

**Comment by Amorano** [comment]
> Hi, sorry for bothering you, but where am i supposed to set the gifski path exactly ? I din't understand what the "set JOV_GIFSKI='C:\gifski-1.14.4'" is meant to be. I've set the cli file of gifski on my path but your repo seems not to detect it. Sorry again and thank for your help

No worries!

You need to set the environment variable "JOV_GIFSKI" to be where the location of your gifski.exe is located. 

In my setup I have gifski in my c:\dev folder:

![image](https://github.com/Amorano/Jovimetrix/assets/225178/32457975-2de0-489e-a773-5f016f6dafe2)

So I use the following to set the gifski path in my comfyui.bat file:

SET JOV_GIFSKI=c:\dev\gifski.exe

HTH

**Comment by OtakuFra** [comment]
awesome, problem solved, thx a lot =)
