### ISSUE TITLE
Text Generator EDGE - WRAP property doesn't seem to work

### ISSUE THREAD

**Issue by ManOrMonster** [Amorano/Jovimetrix#16]
Maybe I'm misunderstanding how this works, but the "WRAP" value for "EDGE" doesn't seem to do anything.

I'd like to wrap long strings like "2023-11-11_150818_883535 [1530266472] [3072x3072] [fennPhoto_v10]" into multiple lines. AUTOSIZE works to fit it all into one line, but then the font is too small.

**Comment by Amorano** [comment]
The edge mode is for wrapping the image, not the text. It is the same edge mode for all the nodes that have it.

I do not have an "auto-wrap text" function in that node. Sorry. The best you can do is split the text yourself -- 
i.e. add carriage returns in the lines
like
this
someplace.

I will add auto-wrap to the list!

**Comment by Amorano** [comment]
> 
> You can close this if you like.

No! Its a good option to have -- a little effort to add, but not much.

**Comment by Amorano** [comment]
> So I was misunderstanding what that property is for. Thanks for the explanation.
> 
> The problem with adding carriage returns is that the string is being passed in automatically from a file name, so now I'll have to figure out how to add carriage returns after so many characters, but at least that's an option.
> 
> You can close this if you like.

So, I am a dum dum. This is actually already in there. If you set auto-fit mode, and change the COLS setting to be something other than 0 it will start to auto-fit the words by wrapping them based on the # of "columns" you select. In the picture you can see I used something larger than your first string (40+ chars) and it allows the line to wrap into 2. If you drop it to around 35 it will be 3ish.

Hope that helps; sorry it was already there an I literally forgot!

![image](https://github.com/Amorano/Jovimetrix/assets/225178/6df2c703-c4a8-4912-9fa5-d1a2de63dcfd)

**Comment by ManOrMonster** [comment]
I did try that (though I was confused by exactly what COLS does since the value doesn't seem to change anything), but "AUTOSIZE" only seems to change the font size to whatever fits on one line. Not sure what I'm doing wrong here. My image size is slightly bigger than your setting in your example, but I also tried 256x256, which made no difference.

<img width="1024" alt="image" src="https://github.com/Amorano/Jovimetrix/assets/3925151/26e874f3-3195-436d-91f5-ca5df1822acf">

**Comment by Amorano** [comment]
If you hold down ctrl+shift with one (or multiple) of my nodes selected, you will see a tooltip pop up that tried to explain them a bit.

I have pushed my current latest, which should resolve the problem and work as intended.

![image](https://github.com/Amorano/Jovimetrix/assets/225178/3177a625-5ca0-4fd5-9e63-4e6a2ce26ef7)

**Comment by ManOrMonster** [comment]
Yes, it works now, and what a great feature! I had no idea about that hidden shortcut.

**Comment by Sorry-Im-Stupid** [comment]
I have a related issue, I can't seem to change width and height. It's not an interactive field for me.

**Comment by Amorano** [comment]
> I have a related issue, I can't seem to change width and height. It's not an interactive field for me. I also can't change the colors, text or background.

Not sure what you mean, not interactive. You can't left-click and drag nor click and get an input box?

What browser/OS?

**Comment by Sorry-Im-Stupid** [comment]
I can't click and drag, it won't give me a popup to input anything, and if I convert it, comfymath's nodes won't plug into it.
I'm on Linux Mint, Firefox

**Comment by Amorano** [comment]
> I can't click and drag, it won't give me a popup to input anything, and if I convert it, comfymath's nodes won't plug into it. I'm on Linux Mint, Firefox

First thing is, my Vectors do not support ComfyMaths.

I develop on Firefox, but Windows, and test on Mac. I have no problems with dragging nor seeing the popup.

Are you using the latest of both the browser and this repository? Jovimetrix should be @1.2.57. My current firefox on Win and Mac is 133.0.3 (64-bit).

If those are all correct, perhaps trying Chrome or some other browser to confirm it is a problem with Linux and not the browser would be a good start.

**Comment by Sorry-Im-Stupid** [comment]
Well I installed your addon yesterday, and it says it's up to date. I haven't updated firefox in a while so I guess I'll give that a go and see if it works. 
If your nodes don't like comfymath, is there a different way to make a vec2 node?

**Comment by Amorano** [comment]
> Well I installed your addon yesterday, and it says it's up to date. I haven't updated firefox in a while so I guess I'll give that a go and see if it works. If your nodes don't like comfymath, is there a different way to make a vec2 node?

You can make VECn nodes With the `VALUE` node. If the browser update doesnt work, you should make this a separate issue so we dont keep pining the original author of this issue. =D

HTH

**Comment by Sorry-Im-Stupid** [comment]
I updated everything and still doesn't work, I actually found the section of the console readout that loads your addon and it is issuing some warnings:
``2024-12-31 14:51:08.718 | ERROR    | Jovimetrix.sup.stream:<module>:36 - NO SPOUT GL SUPPORT
2024-12-31 14:51:08.718 | ERROR    | Jovimetrix.sup.stream:<module>:37 - No module named 'SpoutGL'
2024-12-31 14:51:08.736 | WARNING  | Jovimetrix:__init__:956 - module failed /home/USERNAME/Stable/ComfyUI/ComfyUI/custom_nodes/Jovimetrix/core/device_stream.py
2024-12-31 14:51:08.736 | WARNING  | Jovimetrix:__init__:957 - cannot import name 'window_capture' from 'Jovimetrix.sup.stream' (/home/USERNAME/Stable/ComfyUI/ComfyUI/custom_nodes/Jovimetrix/sup/stream.py)
Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face (unknown file format; error code 0x2)
2024-12-31 14:51:09.404 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.create
2024-12-31 14:51:09.405 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.compose
2024-12-31 14:51:09.585 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.calc
2024-12-31 14:51:09.608 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.device_midi
2024-12-31 14:51:09.691 | INFO     | Jovimetrix.sup.shader:<module>:113 -   vertex programs: 0
2024-12-31 14:51:09.691 | INFO     | Jovimetrix.sup.shader:<module>:114 - fragment programs: 13
2024-12-31 14:51:09.694 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.create_glsl
2024-12-31 14:51:09.695 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.utility.info
2024-12-31 14:51:09.695 | WARNING  | Jovimetrix.core.utility.io:<module>:56 - no gifski support
2024-12-31 14:51:09.695 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.utility.io
2024-12-31 14:51:09.696 | INFO     | Jovimetrix:__init__:989 - ✅ Jovimetrix.core.utility.batch
2024-12-31 14:51:09.696 | INFO     | Jovimetrix:__init__:990 - 59 nodes loaded
``

**Comment by Amorano** [comment]
The warnings are just warnings. Linux doesnt allow device access the same way as everyone else (STREAM READER/WRITER nodes), SPOUT is windows only and GIFSKI is windows/mac only.

And sadly, I do not know how to reformat for github markdown.

I am unsure how to resolve your issue given I just do not aim this library at Linux. Its great if it works, but I just dont have the free time resource to test (multiple) LinuxOS variants.

The bothersome part for me is that the number field doesn't pop up a box, given it is using the core comfy mechanism to do that. I assume the box pops up for other numerical fields, so, I honestly have no clue what could be the issue.
