### ISSUE TITLE
Undefined Stream Reader

### ISSUE THREAD

**Issue by Madhubala-06** [Amorano/Jovimetrix#19]
When loading the graph, the following node types were not found:
📺 StreamReader (jov)
Nodes that have failed to load will show as red on the graph.

**Comment by Amorano** [comment]
Using the latest, I receive no error.
![image](https://github.com/Amorano/Jovimetrix/assets/225178/25319bde-d5e7-4242-808c-617c5f61202b)

Please make sure you are updated -- if the node is part of an old workflow, make sure to pull out a new one -- things change -- this is not a published product.
