### ISSUE TITLE
Very difficult to find specific nodes to target with custom color rules

### ISSUE THREAD

**Issue by var1ableX** [Amorano/Jovimetrix#20]
There's currently no way to filter the nodes that appear "Color Config".

**Comment by Amorano** [comment]
> There's currently no way to filter the nodes that appear "Color Config".

Sorry, you will have to explain a little more of what you mean.

If you mean "filter" as in "start typing into some text line" and have that filter the entire list of node, no, it doesnt do that. 

Feel free to add that feature.
