### ISSUE TITLE
Could you add a text description on nodes

### ISSUE THREAD

**Issue by cardenluo** [Amorano/Jovimetrix#21]
this is a very powerful node group, but the icon confuses me a lot. I have to relearn what the icon means after a while.

**Comment by Amorano** [comment]
> this is a very powerful node group, but the icon confuses me a lot. I have to relearn what the icon means after a while.

First thing, use the tooltips. Select one of my nodes and press SHIFT+CTRL and you will see text descriptions of the parameters.

![image](https://github.com/Amorano/Jovimetrix/assets/225178/86d9714e-dc8b-4d5e-8933-6f4373ca13a0)

There is also a help system being built that [takes you to the wiki](https://github.com/Amorano/Jovimetrix/wiki):

![image](https://github.com/Amorano/Jovimetrix/assets/225178/8193434a-86ec-4cd9-8b11-b50a30f8c45c)

Till then, its just free effort.

**Comment by screan** [comment]
Letting you know a lot of your images are 404 in the wiki. 
<img width="861" alt="Screenshot 2024-03-18 at 12 23 12 AM" src="https://github.com/Amorano/Jovimetrix/assets/4242715/62e8caa0-bd17-4801-a347-cf9dd8a47802">

**Comment by Amorano** [comment]
This is a known issue as that is my custom 404.
