### ISSUE TITLE
Midi

### ISSUE THREAD

**Issue by ttodosi** [Amorano/Jovimetrix#22]
Hey yo, can you provide a midi set up? All these palm trees! Also, maybe about the ticker, my prompts are running out of 1,000,000 miles an hour. Thanks dude

**Comment by Amorano** [comment]
![image](https://github.com/Amorano/Jovimetrix/assets/225178/df3cbdbd-3ce0-4142-9a5b-9542566d28cb)

for the simplest, what is this junk, example. Your value is the raw midi value 0-127 from whatever control surface you have selected. The note is the last note and is obviously specific if you have keys/note value buttons.

The trigger channel will just 0 or 1 if there is something happening.

If you want to drive things from values, you can also use the 0-1 (the normalized range of the value output 0...1).

As another example, using my crappy MPK mini, I have the K1 Dial Control on device channel 1 -- as you can see in the graph used to map the control channel #s.

![image](https://github.com/Amorano/Jovimetrix/assets/225178/14134dfe-fe83-415a-9877-e5b589c4ab52)

when I use the K5 knob, the device value changes to reflect that (5):

![image](https://github.com/Amorano/Jovimetrix/assets/225178/29162c9c-4d00-48bf-8024-b2924647a37c)

HTH!

**Comment by Amorano** [comment]
If you can post an image of your workflow, and the actual error log you are seeing. 

But yes, you need to turn on the auto-q for it to be as "realtime" as possible.

**Comment by ttodosi** [comment]
hi thanks for post, having got around to hooking up yet, soon bomebox

**Comment by Amorano** [comment]
> hi thanks for post, havent got around to hooking up yet, wasn't the idea that you can you use the bpm thing instead of auto-q?. also i'm running this through pinkokio so im not sure everything installs right

The TICK node will indeed pump a steady beat, but that still has to be engaged by the AUTO-Q. There is no way around running "live" without the AUTO-Q submitting Q's for frames.

You can make devices like cameras/midi/etc... poll inside their node and show the real-time video, but that wont actually render in comfy until you prompt into the QUEUE.

As for Pinokio...  seems to be the crux of a few people's issues, not really sure how to solve someone else's wrapper around the thing I did engineering against. If there is some easy solution to using their system, for developers, it is not apparent on a first glance.
