### ISSUE TITLE
any progress on a stereoscopic node? 

### ISSUE THREAD

**Issue by Appolonius001** [Amorano/Jovimetrix#23]
[#question](label:question)
i saw in a reddit post you might be working on one. would love to see some 3d images in a quest 2 :D thanks

**Comment by Amorano** [comment]
It is still on the list!

**Comment by hahajaja** [comment]
Can I share any case files?

**Comment by Amorano** [comment]
> Can I share any case files?

Yeah, if you have exemplar, that would be swell!

**Comment by Amorano** [comment]
I am going to just leave the current node as it is setup; there are a couple of other nodes that provide better keystoning/algos now.
