### ISSUE TITLE
Console log list of links in the Latest update 

### ISSUE THREAD

**Issue by kakachiex2** [Amorano/Jovimetrix#24]
I s this console log list ok or is a bug 
![Screenshot 2024-03-26 120719](https://github.com/Amorano/Jovimetrix/assets/1762112/f048981b-ed4f-4a16-8892-4a0dacd62192)

**Comment by Amorano** [comment]
indeed. The spam was left in the last push. TY for the report!

**Comment by Amorano** [comment]
should be cleared up -- help is now under the ? at the top right

**Comment by kakachiex2** [comment]
Thanks
