### ISSUE TITLE
Import failing on Colab

### ISSUE THREAD

**Issue by BlakeOne** [Amorano/Jovimetrix#26]
Heya, I'm trying to use your node pack on Google Colab (Linux), but I'm getting the below errors when Comfy tries to import your nodes. PS I was able to get it working by rolling back to an old commit from march (50acdbe).

`2024-04-18 20:56:19.577 | ERROR    | Jovimetrix.sup.stream:<module>:33 - NO SPOUT GL SUPPORT

2024-04-18 20:56:19.577 | ERROR    | Jovimetrix.sup.stream:<module>:34 - No module named 'SpoutGL'

ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
Traceback (most recent call last):

  File "_rtmidi.pyx", line 810, in _rtmidi.MidiIn.__cinit__
RuntimeError: MidiInAlsa::initialize: error creating ALSA sequencer client object.`

**Comment by Amorano** [comment]
Correct. You dont have spout installed with collabs, since its windows only.

https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#spout-windows-only

cheers
