### ISSUE TITLE
Batch Images not working 

### ISSUE THREAD

**Issue by jerrydavos** [Amorano/Jovimetrix#28]
Everything is working fine in a single image but batch images is not working in any node for me: 

1) 

![image](https://github.com/Amorano/Jovimetrix/assets/152957217/acf86855-a95a-4570-bbfb-39a6ee782761)

2) Giving Weird Lines (Single Row of Pixels render after Batch ... which is unusable with any other node.. giving error
![image](https://github.com/Amorano/Jovimetrix/assets/152957217/35ef57d0-3b4d-4387-90f7-912f236a0b05)

with the following console error: 

```
F:\Stable Diffusion\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\blendmodes\blend.py:642: RuntimeWarning: invalid value encountered in divide
  out_rgb = np.divide((lower_rgb_part + upper_rgb_part + blended_rgb_part), out_alpha[:, :, None])
Prompt executed in 0.87 seconds
```

LOGS: 
[Error Log.txt](https://github.com/Amorano/Jovimetrix/files/15061070/Error.Log.txt)

.
.
.

I have updated comfy, JOV nodes....  Reinstalled, Deleted and git cloned, Downgraded too to check if it works but previous commit also broke the nodes... 
![image](https://github.com/Amorano/Jovimetrix/assets/152957217/c2ac04e9-0e33-406b-bce1-d326d838acf8)

Then I Tried uninstalling numba, blendmodes... others and reinstalling with cmd but still no luck...... some dependencies are dependent on others... and other dependencies and versions are mismatching with red errors :/

![image](https://github.com/Amorano/Jovimetrix/assets/152957217/df30866b-8cc7-4ffa-a29d-280e651a601b)

.
.

![image](https://github.com/Amorano/Jovimetrix/assets/152957217/3f161b6e-e057-4157-9ed1-7e58d50c47b2)

**Comment by Amorano** [comment]
I have not updated the nodes to work with batch. You need to convert to list at the moment. :(
