### ISSUE TITLE
"SHAPE GEN" problems with input WH (VEC2)

### ISSUE THREAD

**Issue by Maelstrom2014** [Amorano/Jovimetrix#33]
Here the problem
https://ibb.co/vqYy7ZQ
please tell if its a bug or smth not right with my installation?

**Comment by Amorano** [comment]
So, I dont know what a "compose vec2" node is -- I have no translation for whatever that is making -- which it looks like its making an "array" of numbers not a tuple [[x], [y]] not (x, y).

I will check if I can make a translation for the ComfyMath extension node (I do not use that -- my repo does all that -- use a value node). Same for all the math operations:

![image](https://github.com/Amorano/Jovimetrix/assets/225178/b142a478-5c9b-4ee3-810b-b635df252894)

**Comment by Amorano** [comment]
![image](https://github.com/Amorano/Jovimetrix/assets/225178/c7da0481-2e96-4090-978e-2fefed07288c)

so, looking at that node, it makes a LIST not a TUPLE -- so it is seeing the X as one entry and Y as another and making a tensor batch of (2).

I cant really fix this as its a problem in the ComfyMath node itself since it is pushing out a list [x, y] and not a list of coordinates [[x, y]].

**Comment by Maelstrom2014** [comment]
BTW, OLD "SHAPE GENERATOR" worked ok with VEC2, after update my WF not work anymore, that I need to rebuild it.

**Comment by Amorano** [comment]
> BTW, OLD "SHAPE GENERATOR" worked ok with VEC2, after update my WF not work anymore, that I need to rebuild it. Tried to find commit with that edition, but fail to find. May be you can help?

Correct, because I was not working the proper way in Comfy. ComfyUI treats all lists as a list. If you want to make things like "coordinates" work you should use a dict {x:0, y:0} or a list of "list" or "tuple" [(x, y)] -- otherwise no one can tell if you are sending in coordiantes or just a number line. 0, 1, 2, 3,, 5....

I had an idea to try and hackish around getting the output type from the ComfyMath slot, but it is more work than it needs to be.

I have only just started doing documentation; hopefully some videos and more workflows too soon. 

the image of the workflow you posted doesnt look like it would be much work to convert. If you want to post another screenshot or a workflow that you want to see get translated, I can try to help speed that up for you.

**Comment by Maelstrom2014** [comment]
Another Question, If I make input form node "VALUE JOV", queue not starting. 

Im makein a range, and want SHAPE GEN animate moving rectangle.. With new version its not working. 
in WH I put static frame size, and in XY I put a range of moving Y.

New version of whis NODE have problems with ranges? 
thats a screenshot:
https://ibb.co/hXR3yZG

**Comment by Amorano** [comment]
> Another Question, If I make input form node "VALUE JOV", queue not starting.
> 
> Im makein a range, and want SHAPE GEN animate moving rectangle.. With new version its not working. in WH I put static frame size, and in XY I put a range of moving Y.
> 
> New version of whis NODE have problems with ranges? thats a screenshot: https://ibb.co/hXR3yZG

![works](https://github.com/Amorano/Jovimetrix/assets/225178/1b21485f-1a91-42b3-9021-aeb61c4096e9)

take this image and drag it into comfy (it has the workflow). If that doesnt work, then yeah there maybe a problem; however, in your screen shot it has the output in the Akashic (that means it ran) -- you dont have it actually plugged into anything IN the shape generator node.

**Comment by Maelstrom2014** [comment]
> > Another Question, If I make input form node "VALUE JOV", queue not starting.
> > Im makein a range, and want SHAPE GEN animate moving rectangle.. With new version its not working. in WH I put static frame size, and in XY I put a range of moving Y.
> > New version of whis NODE have problems with ranges? thats a screenshot: https://ibb.co/hXR3yZG
> 
> ![works](https://private-user-images.githubusercontent.com/225178/335825177-1b21485f-1a91-42b3-9021-aeb61c4096e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzI2NTMsIm5iZiI6MTcxNzI3MjM1MywicGF0aCI6Ii8yMjUxNzgvMzM1ODI1MTc3LTFiMjE0ODVmLTFhOTEtNDJiMy05MDIxLWFlYjYxYzQwOTZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQyMDA1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjZlMzRhMTlkZDRhNmNlYjRkMjU5NmUwMDU0MWRiMDE5NTQ2NWY5MGVkZTg0ZjExNjZkNjFhZTAzZDg2N2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CaKVBYT-9n47KZEszdJ6LnfWTjyrqNGh2ZgKIUpMeEk)
> 
> take this image and drag it into comfy (it has the workflow). If that doesnt work, then yeah there maybe a problem; however, in your screen shot it has the output in the Akashic (that means it ran) -- you dont have it actually plugged into anything IN the shape generator node.

I mean input to VALUE JOV node. I try to make it form a right value for inputing to SHAPE GEN.

**Comment by Maelstrom2014** [comment]
Problems 1):
Can you start this work flow? I can not.
![workflow (6)](https://github.com/Amorano/Jovimetrix/assets/10183119/6fe3244e-1a96-47b9-87ef-47e44bddb16a)

**Comment by Amorano** [comment]
ok! thank you for the clear example. I cleaned up a few things in the defaults for the shape node and a few others, and re-wired the value node a bit to be more clear with the inputs vs. defaults.

You wont have to convert a widget anymore -- just plug in your default. The widget value will be used as a default if there is no input and its a value that can be used in the output.

![workflow](https://github.com/Amorano/Jovimetrix/assets/225178/7af257e6-aaf9-45a0-a01c-1f61085d3d7c)

I will do some more testing and push the changes in tomorrow.

Thank you for the bug report!

**Comment by Amorano** [comment]
![working](https://github.com/Amorano/Jovimetrix/assets/225178/98aba273-b423-4e20-aaa7-78e3abc3f3dd)

ran through some tests and went back to check the original use-case. Seems to have cleaned all that messy stuff up. 

You can see here you can now also just use a single float, int, etc... and the remaining values will self-populate based on the last value, or an override default. All the fall through values!

Let me know if you find any weirdness -- and any other use-cases with other 3rd party nodes -- I will try to accommodate any translators for their type(s).

HTH

**Comment by Maelstrom2014** [comment]
thanx for fixes! I'll try tomorrow how it inputs a ranges of numbers. Did you test it?

**Comment by Amorano** [comment]
> thanx for fixes! I'll try tomorrow how it inputs a ranges of numbers. Did you test it?

Do you mean with batches? Works as it should -- seems good.

![image](https://github.com/Amorano/Jovimetrix/assets/225178/1febc7e2-f0ae-49e1-987d-bf29a6005ec0)

**Comment by Maelstrom2014** [comment]
HI, again! 
I updated with "git pull" today. May be I need delete and reinstall? Cant check updated. Here is two problems:
1) parameter of shape points not visible by default.
2) Cant converts widget (ex WH or XY) to outer input 
![prob2](https://github.com/Amorano/Jovimetrix/assets/10183119/e3f7745e-45b2-4fab-ab81-fead076f6398)
![prob3](https://github.com/Amorano/Jovimetrix/assets/10183119/63f86f19-9cbb-4856-939c-42c18494ba2a)

**Comment by Amorano** [comment]
> HI, again! I updated with "git pull" today. May be I need delete and reinstall? Cant check updated. Here is two problems:
> 
>     1. parameter of shape points not visible by default.
> 
>     2. Cant converts widget (ex WH or XY) to outer input
>        ![prob2](https://private-user-images.githubusercontent.com/10183119/336073963-

On no!

So for the first one, you dont see that parameter unless you change the shape -- the sides are only visible for the POLYGON type.

The second one looks like a bug, 100%. I have patched that up and will push it shortly.

Thank you again. I checked a few more nodes from the packs you are using to make sure things work back and forth for list/single values.

Cheers!
