### ISSUE TITLE
AKASHIC SHOW WRONG INFO

### ISSUE THREAD

**Issue by Maelstrom2014** [Amorano/Jovimetrix#34]
AKASHIC SHOW WRONG INFO. 
Here is a comparison:

![akash](https://github.com/Amorano/Jovimetrix/assets/10183119/8dd3e107-d402-4163-ad26-b41bc6103f4d)

**Comment by Maelstrom2014** [comment]
It cant show list with different batches inside. It shows all like list

**Comment by Amorano** [comment]
> It cant show list with different batches inside. It shows all like list

yeah, so, that is the CORRECT info. There are 17 images in the batch(es). It reports all the images.

You are looking for it to say 17xWxHxC  that is not how I wanted it formatted.
