### ISSUE TITLE
spout example

### ISSUE THREAD

**Issue by drmbt** [Amorano/Jovimetrix#35]
trying to implement your spout setup, its not very self explanatory. got any tips on how to configure, or a workflow?

**Comment by Amorano** [comment]
For sure! I only use the Spout SDK as I dont use Touch Designer like the people who asked for the spout support. But, easy enough. The Stream Reader set to Spout will read the stream name in the URL field.

The separate Spout Writer will write out.

Here is a simple example using the SDK apps to read/write:

![image](https://github.com/Amorano/Jovimetrix/assets/225178/273ed598-649b-411b-b571-345079f8f218)

[spout.json](https://github.com/user-attachments/files/15890456/spout.json)

Let me know if that is not working. I am using a local version I have not pushed yet, but that is the same setup in either case.

Cheers
