### ISSUE TITLE
Does this project only support Windows? 

### ISSUE THREAD

**Issue by SongOnWater** [Amorano/Jovimetrix#37]
Hi, I appreciate your brilliant work. But does your project on support Windows platform? how about Linux and Mac? I tried install and run the code on a Mac M2, and failed of several example workflows from the example repository.

**Comment by Amorano** [comment]
> Hi, I appreciate your brilliant work. But does your project on support Windows platform? how about Linux and Mac? I tried install and run the code on a Mac M2, and failed of several example workflows from the example repository.

My primary target is Windows, yes. I do not have a Mac to test. I do run Linux in a docker to test out updates though; that is why the next update reduces a lot of the audio things that mess with Linux distros.

If I had a way to test Mac, I would add it to the test chain, so if you have any suggestions, I'd love to make sure it works across all the platforms.

**Comment by Amorano** [comment]
I reduced the dependencies and have pushed a large change-set that may resolve some issues with Mac. Hopefully that will resolve things for you.
