### ISSUE TITLE
how to use the queue

### ISSUE THREAD

**Issue by Ginushmal** [Amorano/Jovimetrix#38]
how can i use the Jovimetrix Queue Node to process one image at a time
![image](https://github.com/Amorano/Jovimetrix/assets/60034915/e7e0a695-ca02-40b0-89dd-39afd1318478)

doing this just process one image and stop, but I can click Queue prompt 365 times and get them to process but I think there must be a better way right

**Comment by Amorano** [comment]
> how can i use the Jovimetrix Queue Node to process one image at a time 
> doing this just process one image and stop, but I can click Queue prompt 365 times and get them to process but I think there must be a better way right

Correct, when the VAL is set to 0 it will iterate the list. 

If you turn on BATCH == you will get a batch (single Tensor) with 365 images inside it.

Keep in mind all the images must be the same size (for batch mode); I do not auto-upscale/downscale on those.

As an example image:

![image](https://github.com/Amorano/Jovimetrix/assets/225178/12721a67-0a4c-4f20-a507-1f03b2ff7fc5)

Let me know if that is unclear.

HTH

**Comment by Amorano** [comment]
Just use the auto-queue?

![image](https://github.com/Amorano/Jovimetrix/assets/225178/af785c9b-299f-43dd-9b50-cdf14fb65151)

**Comment by Ginushmal** [comment]
Oh no..🥲 didn't know that was an option , thank u so much... ❤
