### ISSUE TITLE
Wiki images broken

### ISSUE THREAD

**Issue by jffaust** [Amorano/Jovimetrix#39]
Hello!

Thank you for making this custom node pack. The nodes are very interesting. 

I was browsing the wiki to better understand the features but I noticed a lot of the images are broken:
![image](https://github.com/user-attachments/assets/3a812040-9836-4c86-948e-724faec05c14)

It would really help to have those fixed.

**Comment by Amorano** [comment]
> Hello!
> 
> Thank you for making this custom node pack. The nodes are very interesting.
> 
> I was browsing the wiki to better understand the features but I noticed a lot of the images are 
> broken:
> It would really help to have those fixed.

Indeed. I have updated them to match the ones used for the help system -- the images you should see there are the exact images in the help on the nodes that comes from [Jovimetrix Examples](https://github.com/Amorano/Jovimetrix-examples/)

The image there will just be the node which then points back to the Jovimetrix Examples image. For something like the TICK node it looks like:

![image](https://github.com/user-attachments/assets/73511101-3eda-4872-b67d-bfb1d4ad6478)

Hopefully they are all in sync (minus the route node) so when I update the examples repository they should update here as well.

Cheers for the reminder =D

**Comment by Amorano** [comment]
this is long since resolved. If you are using a version that is older than the current (as of two weeks) then I suggest updating. The help is now in both spots (new comfyui sidebar they added) if you have that on or in the old menu if you are not using the new top/bottom bar.
