### ISSUE TITLE
Input and Output Namings

### ISSUE THREAD

**Issue by lunanane** [Amorano/Jovimetrix#40]
Hey, 
this is a feedback more than an issue. I felt the need to write you and hope it is well received.
I realy like the project a lot and coming from decade of node based programming and writing my own shader pipelines, i was hooked on joining the coding on this in particular with the possibilities for more generative input from glsl nodes.

However, I think the emoji icon naming you introduced is not a good idea!  Add-Ons for node based environments really live from how quickly their data-flow and respective data-types are understandable. In this case, the usability is quiete hindered by the unclear emoji namings that have zero explanation to them.clipboard symbol, unicorn symbol, crytal ball symbol - i can make wild guesses what it means and in some I am even getting it, but in many instances I could not figure it out and didnt find any clear explanation either.

I am having usualy no problem to use any node based editor, but Jovimetrix has realy cost me a lot of time already trying to figure out very basic concepts that i have been putting up many times in other node based environments like unity or unreal shader graph, vfx grap, vvvvv, blender geometry nodes etc.

So yes, I think that a renaming of parameters would be needed for othere devs eventually beeing able to join actually and for users to really benefit from it.

Then, however, it is for me personally the most promising node set out there so far!

**Comment by Amorano** [comment]
Sorry, but the emoji are not changing. They are already in workflows attached to things. If I could remap them without breaking a bunch of existing workflows I might consider it.

There are numerous help and tooltips that explain the functionality, like ANY other software with iconography.
