### ISSUE TITLE
A BUG BLOCKING COMFYUI UI

### ISSUE THREAD

**Issue by Maelstrom2014** [Amorano/Jovimetrix#41]
Hi!
Can't work with it, disable this custom node.
BUG: It disables right-click save image on preview. And I'm sure something else.

**Comment by Amorano** [comment]
> Hi! Can't work with it, disable this custom node. BUG: It disables right-click save image on preview. And I'm sure something else.

Sorry, I need a little more than what you have. 

Cant work with it what?

Are you trying to say that using the "disable node" feature of the ENV is not working and disabling the right-click on image preview nodes?

And I am sure something else? doesnt help either -- please write up a clear problem or share a file so I can actually fix any bugs.

**Comment by Maelstrom2014** [comment]
> > Hi! Can't work with it, disable this custom node. BUG: It disables right-click save image on preview. And I'm sure something else.
> 
> Sorry, I need a little more than what you have.
> 
> Cant work with it what?
> 
> Are you trying to say that using the "disable node" feature of the ENV is not working and disabling the right-click on image preview nodes?
> 
> And I am sure something else? doesnt help either -- please write up a clear problem or share a file so I can actually fix any bugs.

You node cases a ui blocking (bug) in comfyui. Only way to solve a problem - to disable your node, so did I.
A BUG:  try to make preview node, run anything to input in preview node. When picture appears in preview windows try to save it (normal functionality) with right-click than save image. Your custom node in comfyui block with action. And I think it blocks something else.

**Comment by Amorano** [comment]
> > > Hi! Can't work with it, disable this custom node. BUG: It disables right-click save image on preview. And I'm sure something else.
> > 
> > 
> > Sorry, I need a little more than what you have.
> > Cant work with it what?
> > Are you trying to say that using the "disable node" feature of the ENV is not working and disabling the right-click on image preview nodes?
> > And I am sure something else? doesnt help either -- please write up a clear problem or share a file so I can actually fix any bugs.
> 
> You node cases a ui blocking (bug) in comfyui. Only way to solve a problem - to disable your node, so did I. A BUG: try to make preview node, run anything to input in preview node. When picture appears in preview windows try to save it (normal functionality) with right-click than save image. Your custom node in comfyui block with action. And I think it blocks something else. I spent several days to find what rotten apple node causes this problem.

Thank you.

![image](https://github.com/user-attachments/assets/73210232-d9f7-410b-a38a-dbd2acf39997)

I have patched that bug and pushed the change. Let me know if that resolves the issue.
