### ISSUE TITLE
[FR] Transform (but using depth map)

### ISSUE THREAD

**Issue by softyoda** [Amorano/Jovimetrix#42]
Using euler rotate camera, and translate in x,y,z space using depth-map projection (maybe fov change as well) (and apply transform from using depth to another rgb image)

**Comment by Amorano** [comment]
Interesting idea! Perhaps this is something that could be done with a shader already?

I am trying to put any future compositing or transformation operations in as GLSL shaders since they are much faster for that kind of thing.
