### ISSUE TITLE
Help panel broken, tooltips missing

### ISSUE THREAD

**Issue by Kadah** [Amorano/Jovimetrix#44]
The help button opens a broken panel. Unable to get any tooltips to show using SHIFT+CTRL. The context menu on any node does not have a help the option I've seen in various screenshots. Not sure why its broken.

![image](https://github.com/user-attachments/assets/b9af113d-7eb6-4c76-a7f9-25f6bb1d2dca)

Installed though Manager on clean fresh install of Comfy 55ad9d5f8c8b906102313e894e471d2f5e833577 with no other extensions installed. Test on both Chrome and Firefox.

Was trying to decode the emoji labels. Ended up having to reference from the source code.

**Comment by Amorano** [comment]
Oh no!  Ok, so you have the latest comfy but are not using the new frontend? correct?

And you also do or do not have the new Manager Bar turned on?

There should be tooltips for most fields -- if those are not showing up, this is also a bug. :(

**Comment by Amorano** [comment]
And could you post the console from the browser? I am sure something is tossing an error

**Comment by Kadah** [comment]
> Oh no! Ok, so you have the latest comfy but are not using the new frontend? correct?

Correct, old frontend currently. I will possibly switch soon as the new one is working on fixing accessibility issues.

> And you also do or do not have the new Manager Bar turned on?

New manager bar, switching back to legacy has no effect.

All console output on chrome:
```
GET http://127.0.0.1:8189/userdata/workflows%2F.index.json 404 (Not Found)
components-manager.js:767 Empty components: policy ignored
GET http://127.0.0.1:8189/userdata/workflows%2F.index.json 404 (Not Found)
```
I've never seen tooltips in Comfy. Is that something custom you're doing?

**Comment by Amorano** [comment]
Correct. The tooltips are my own system, however, they have recently added a system for it. That requires that node authors actually add the data to the fields. Mine will work in either case.

![image](https://github.com/user-attachments/assets/afc0674a-3331-427a-a137-f495d2facba0)

You "should" be seeing them, in either the new front-end or the old.

I tried to tweak the popup, but they are making a lot of quick patch changes to keep most of the older nodes from breaking when they push out the PR 2666 (next week I think).

Sorry for any weirdness as it transitions! Let me know if those tweaks help

**Comment by Kadah** [comment]
That appears to work.

![image](https://github.com/user-attachments/assets/f7acc2ad-fb13-40da-aaa9-caa1f8baf019)

Node titles aren't readable on light theme, but that type of accessibility is pretty bad in across a lot of Comfy still currently.

**Comment by Amorano** [comment]
> That appears to work.
> 
> ![image](https://private-user-images.githubusercontent.com/751209/356804942-f7acc2ad-fb13-40da-aaa9-caa1f8baf019.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTMzODYsIm5iZiI6MTcyMzMxMzA4NiwicGF0aCI6Ii83NTEyMDkvMzU2ODA0OTQyLWY3YWNjMmFkLWZiMTMtNDBkYS1hYWE5LWNhYTFmOGJhZjAxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxODA0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWZiMThjNDg1NDk5MjVkNWI3ZWY0ZWM5NGI4NGYzZGY1NjUxMTE0MjRmNTY5YTMyMDI2Mjk0ZWJmNjE4YjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XQ-Sr_Ed7KcL4nroCY5ma0V8jS1sKQdL88GVlA2d0fU)
> 
> Node titles aren't readable on light theme, but that type of accessibility is pretty bad in across a lot of Comfy still currently.

Yeah, I will see if I can make the color better -- looks like I am probably just using the stylesheet text color and not actually running it through the contrast function =D

**Comment by Kadah** [comment]
The auto-contrast was one of the fixes add to the new front end. Previously it only enabled if the current theme had the id `light`, guessing friends were successful in getting it made a manual option. Ideally the theme should be be able to set the pallet colors, but that is a ComfyUI issue. :p

On your end, the emojis are often pretty hard for me to discern. Some were blending together last time I was trying to use them and had to instead memories their position on each node class as referenced from source.
