### ISSUE TITLE
Support for TLS/SSL key and certfile for Stream Writer node

### ISSUE THREAD

**Issue by jkcarney** [Amorano/Jovimetrix#45]
I have a self contained, dockerized application that uses a webcam in browser (necessitating SSL). I'm using the Stream Writer node to publish the result of each ComfyUI call in real time. The problem is that because the frontend needs to be https, it cannot access a mixed use resource (http) that are published from the stream writer node. 

 Currently, it seems that the Stream Writer node is hard coded to always publish on http rather than configurable with a keyfile and certfile to serve its resource on https. ComfyUI has a `--tls-keyfile` and `--tls-certfile` option already, so its possible to inherit those configuration options.

**Comment by Amorano** [comment]
Thanks! I will look into adding this asap!

**Comment by Amorano** [comment]
I made a few tweaks and it seems to cover the use-case of HTTPS using the same key/cert that you use for ComfyUI:

https://youtu.be/u4nR4NkeKq8

This is in the latest push. Let me know if this resolves the issue!

HTH!

**Comment by jkcarney** [comment]
Thanks, this resolved the issue. Really appreciate the quick turnaround!
