### ISSUE TITLE
Modules Not Visible in ComfyUI

### ISSUE THREAD

**Issue by crafter312** [Amorano/Jovimetrix#46]
I have installed the Jovimetrix suite of notes in ComfyUI via the ComfyUI Manager. Despite the fact that the REAME implies that that's all I should have to do, none of the Jovimetrix nodes actually show up in the GUI (i.e. **there is no node menu tab for Jovimetrix, and none of the modules show up when I search for them**).

The console verifies that I do indeed have the node pack installed, as it shows up in my list of installed nodes:

![image](https://github.com/user-attachments/assets/853cc280-f15e-4473-8869-f7305ffa784b)

Additionally, the following error shows up in the console:

`2024-08-22 09:28:51.656 | WARNING  | Jovimetrix.core.utility:<module>:51 - no gifski support`

The only other thing I've done beyond simply installing Jovimetrix through the manager is to install `cupy`, since this was also missing. As far as I can tell, `gifski` doesn't appear to be a python package, so I am unsure of how to proceed with fixing this issue from here (assuming that `gifski` missing is the reason why none of the nodes show up).

**Comment by Amorano** [comment]
First thing, what version of ComfyUI? 

The new release will only work with the new frontend. You will need to be using frontend 1.2.27 or newwer.

Correct, GIFSKI is a separate install, as pointed out in the docs. [if you dont setup GIFSKI](https://github.com/Amorano/Jovimetrix/wiki/B.-ASICS#gifski-export) it will report it being offline. You need to setup your environment where it lives.

![image](https://github.com/user-attachments/assets/cbe62e97-0318-41ca-9102-a665dee7250f)

If you see that, without an error, all the nodes loaded. Scroll up and show the console where I print out the nodes loading or the errors it will have if they didnt.

**Comment by crafter312** [comment]
Whatever you changed fixed it! I now am able to see all the nodes in the menu. I still get the GIFSKI error since I don't have that set up as you mentioned, but that's a separate issue and I'll look into that later. Thanks for the help!

**Comment by crafter312** [comment]
One side question I do have though is how do I set the necessary environment variable for the GIFSKI setup? Is this a Windows environment variable or do I have to mess with the ComfyUI settings somewhere?

**Comment by Amorano** [comment]
> One side question I do have though is how do I set the necessary environment variable for the GIFSKI setup? Is this a Windows environment variable or do I have to mess with the ComfyUI settings somewhere?

Correct, that is for your windows environment to tell ComfyUI where I can grab gifski.exe to use as the execution engine for the conversion. =D
