### ISSUE TITLE
Color Match LUT USER_MAP mode

### ISSUE THREAD

**Issue by dryodryo** [Amorano/Jovimetrix#48]
Hi, can you update the node reference docs to describe usage of the Color Match LUT USER_MAP mode? I'm at a loss to understand what it's doing and how it works. I didn't see any .CUBE files in the installation directory, so I guess you're building and applying a LUT on the fly? 

I tried it and got very strange results.

Also do not understand the VAL parameter, what does it do?

It's great that you have added tooltips! The ones in the Color Match node are not up to date, the MODE tooltip is wrong and the VAL tooltip is just a circular definition that says "Value"

Thanks again

**Comment by Amorano** [comment]
> Hi, can you update the node reference docs to describe usage of the Color Match LUT USER_MAP mode? I'm at a loss to understand what it's doing and how it works. I didn't see any .CUBE files in the installation directory, so I guess you're building and applying a LUT on the fly?
> 
> I tried it and got very strange results.
> 
> Also do not understand the VAL parameter, what does it do?
> 
> It's great that you have added tooltips! The ones in the Color Match node are not up to date, the MODE tooltip is wrong and the VAL tooltip is just a circular definition that says "Value"
> 
> Thanks again

Correct. That will generate a LUT based on the second input. I will try to do some more passes on the tooltips and help. Just been waiting for ComfyUI to settle into the new frontend.

Cheers for the reports!

**Comment by Amorano** [comment]
![image](https://github.com/user-attachments/assets/fbcd401f-f403-4ff3-aede-90038c9d85aa)

I havent double checked the output table on anything yet, but, I added another node to get a little more tonal information -- and hopefully the .cube output is actually correct. I have a saver written as well, just want to test it all actually makes proper (3D) LUTs.

The palette output is basically a 1D lut.

**Comment by Amorano** [comment]
going to assume this resolves the request as its been a few days =D
