### ISSUE TITLE
Node colors - How do I change the node colors?

### ISSUE THREAD

**Issue by Vigilence** [Amorano/Jovimetrix#54]
I would like to change the top part of the node to a different color then the base part.  Is this possible with this node?  If so how?  I checked the wiki but I didn't find anything.

I checked a [video](https://www.youtube.com/watch?v=QrjDYPvUL7w) posted on reddit and it seems that the latest comfyui [d043997](https://github.com/comfyanonymous/ComfyUI/commit/d043997d30d91ab057f770d3396c2e288e37b38a) doesn't support this atm.

**Comment by Amorano** [comment]
> I would like to change the top part of the node to a different color then the base part. Is this possible with this node? If so how? I checked the wiki but I didn't find anything.
> 
> I checked a video posted on reddit and it seems that the latest comfyui [d043997](https://github.com/comfyanonymous/ComfyUI/commit/d043997d30d91ab057f770d3396c2e288e37b38a) doesn't support this atm.

It does and doesnt. The colorizer needs to be reworked at the moment since everything is now in the side panel.

I will iterate it up now that the new frontend is fully released! 

Sorry about that, but thanks for the reminder!

**Comment by Vigilence** [comment]
Thank you for taking the time to reply and for the update!

**Comment by dachangqing** [comment]
> > 我想将节点的顶部更改为与底部不同的颜色。这个节点可以做到这一点吗？如果可以，该怎么做？我查看了 wiki，但没有找到任何内容。
> > 我查看了 reddit 上发布的视频，似乎最新的 comfyui[d043997](https://github.com/comfyanonymous/ComfyUI/commit/d043997d30d91ab057f770d3396c2e288e37b38a)目前不支持此方式。
> 
> 确实如此，但事实并非如此。着色器现在需要重新设计，因为现在所有内容都在侧面板中。
> 
> 现在新的前端已经完全发布，我将对其进行迭代！
> 
> 很抱歉，但还是感谢您的提醒！

Is the iteration done? I still cannot change the color of the top of the node

**Comment by Amorano** [comment]
> > > 我想将节点的顶部更改为与底部不同的颜色。这个节点可以做到这一点吗？如果可以，该怎么做？我查看了 wiki，但没有找到任何内容。
> > > 我查看了 reddit 上发布的视频，似乎最新的 comfyui[d043997](https://github.com/comfyanonymous/ComfyUI/commit/d043997d30d91ab057f770d3396c2e288e37b38a)目前不支持此方式。
> > 
> > 
> > 确实如此，但事实并非如此。着色器现在需要重新设计，因为现在所有内容都在侧面板中。
> > 现在新的前端已经完全发布，我将对其进行迭代！
> > 很抱歉，但还是感谢您的提醒！
> 
> Is the iteration done? I still cannot change the color of the top of the node

I made a first pass but still need to polish it before I push. Probably tomorrow afternoon.

Sorry for the wait!

**Comment by dachangqing** [comment]
> > > > 我想将节点的顶部更改为与底部不同的颜色。这个节点可以做到这一点吗？如果可以，该怎么做？我查看了wiki，但没有找到任何内容。
> > > > 我查看了reddit上发布的视频，似乎最新的 comfyui [d043997](https://github.com/comfyanonymous/ComfyUI/commit/d043997d30d91ab057f770d3396c2e288e37b38a)目前不支持这种方式。
> > > 
> > > 
> > > 确实如此，但事实并非如此。着色器现在需要重新设计，因为现在所有的内容还是都在侧面板中。
> > > 现在新的前置已经完全发布，我将由此进行迭代！
> > > 很抱歉，但感谢您的提醒！
> > 
> > 
> > 迭代完成了吗？我仍然无法改变节点顶部的颜色
> 
> 我已经完成了第一遍，但在发布之前还需要完善一下。可能明天下午吧。
> 
> 抱歉让您久等了！

Ok, thanks for your efforts! I'm looking forward to it!

**Comment by Amorano** [comment]
> Ok, thanks for your efforts! I'm looking forward to it!

Sorry that took a little extra! First pass on the new picker panel is in there.

![image](https://github.com/user-attachments/assets/e6f20746-d0fa-4cd0-b36b-667afe74135e)

Still needs a little styling polish, but the new picker should pop up for the selection and maintain your choices between sessions (saved in the config) once again.

Let me know if that resolves for everyone!

**Comment by Xenodimensional** [comment]
My colours panel is empty in Opera :(

![image](https://github.com/user-attachments/assets/8acc6e37-95db-40b2-bf68-c4739b3aacac)

Same thing in Firefox:

![image](https://github.com/user-attachments/assets/bfd52a6b-514d-4672-b64b-3b05bfc7e2ea)

Latest version of Comfy and Jovimetrix. This message from the command window seems like it might be relevant:

`FETCH DATA from: H:\ComfyUI_windows_portable_nu\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
2024-09-25 21:34:27.441 | ERROR    | Jovimetrix:jovimetrix_config_post:800 - bad config {'id': 'JOVIMETRIX 🔺🟩🔵.Color
🎨.Highlight'}
Error handling request
Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable_nu\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_windows_portable_nu\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_windows_portable_nu\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_windows_portable_nu\ComfyUI\server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_windows_portable_nu\ComfyUI\server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_windows_portable_nu\ComfyUI\server.py", line 77, in cors_middleware
    response.headers['Access-Control-Allow-Origin'] = allowed_origin
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'headers'`

**Comment by Amorano** [comment]
> My colours panel is empty in Opera :(
> 
> ![image](https://private-user-images.githubusercontent.com/66627464/370692998-8acc6e37-95db-40b2-bf68-c4739b3aacac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODYwMDUsIm5iZiI6MTcyNzI4NTcwNSwicGF0aCI6Ii82NjYyNzQ2NC8zNzA2OTI5OTgtOGFjYzZlMzctOTVkYi00MGIyLWJmNjgtYzQ3MzliM2FhY2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE3MzUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MDIyOWE0Zjg4M2Q2ZDg2NjQ4YWUzMDJhNWM3OWRhMTIwOTRjOTYwZDkzMjRiNjdiNGJkNzE4Yzc3Y2VmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mOlOMk9WQHAUv5-hJjjldrpNgdMn9vE1YKx1RUKfoTQ)
> 
> Same thing in Firefox:
> 
> ![image](https://private-user-images.githubusercontent.com/66627464/370693598-bfd52a6b-514d-4672-b64b-3b05bfc7e2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODYwMDUsIm5iZiI6MTcyNzI4NTcwNSwicGF0aCI6Ii82NjYyNzQ2NC8zNzA2OTM1OTgtYmZkNTJhNmItNTE0ZC00NjcyLWI2NGItM2IwNWJmYzdlMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE3MzUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOTlmNDM0ZmMyZDlmZGRjZThhZTk4YTFhNDk0NGUzZjgxYTcyZDU4N2EwYmU0MDE3NTVlOTE0NDA3YjY5NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.djCrFBGEjeMVrwcyi_15if_zPeHvIIprcThH8w2yXug)
> 
> Latest version of Comfy and Jovimetrix. This message from the command window seems like it might be relevant:
> 
> `FETCH DATA from: H:\ComfyUI_windows_portable_nu\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE] 2024-09-25 21:34:27.441 | ERROR | Jovimetrix:jovimetrix_config_post:800 - bad config {'id': 'JOVIMETRIX 🔺🟩🔵.Color 🎨.Highlight'} Error handling request Traceback (most recent call last): File "H:\ComfyUI_windows_portable_nu\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_windows_portable_nu\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_windows_portable_nu\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_windows_portable_nu\ComfyUI\server.py", line 63, in cache_control response: web.Response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_windows_portable_nu\ComfyUI\server.py", line 141, in origin_only_middleware response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI_windows_portable_nu\ComfyUI\server.py", line 77, in cors_middleware response.headers['Access-Control-Allow-Origin'] = allowed_origin ^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'headers'`

Not sure what the problem maybe, other than a corrupt configuration file?

You should:

1) close comfyui in browser
2) shut down comfyui
3) rename the config.json in the ComfyUI/custom_nodes/Joviemetrix folder (or remove)
4) startup comfyui again.

if that doesnt resolve the issue I would need a little more information from your browser and console log for comfy.

**Comment by Amorano** [comment]
I am assuming this is resolved.
