### ISSUE TITLE
Error on Console After New Update: create_glsl.py and enum.py

### ISSUE THREAD

**Issue by Orenji-Tangerine** [Amorano/Jovimetrix#56]
![image](https://github.com/user-attachments/assets/6ef42327-2312-43d6-bb49-0f19e963e859)

module failed A:\ComfyUI\custom_nodes\Jovimetrix\core\create_glsl.py
cannot import name 'EnumType' from 'enum' (A:\ComfyUI\python\lib\enum.py)

Works fine under commit 54d61c3

**Comment by Amorano** [comment]
Are you sure you are on the latest commit? There is no import for Enum in that file.

**Comment by Amorano** [comment]
> ![image](https://private-user-images.githubusercontent.com/172998895/365687451-6ef42327-2312-43d6-bb49-0f19e963e859.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDM2MjgsIm5iZiI6MTcyNTkwMzMyOCwicGF0aCI6Ii8xNzI5OTg4OTUvMzY1Njg3NDUxLTZlZjQyMzI3LTIzMTItNDNkNi1iYjQ5LTBmMTllOTYzZTg1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNzM1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjI1YzQ1NjZlNjA5YzY0MzRmMTMyZTkwMzgwY2EyNDQzOTI4YWMwZDJhZGQyMjdlNDliZjU4MGYwNGUzZjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0QSutRG6d4DUoJw0_lmDqeqk2eZT7GydAFyT9vuigPs)
> 
> module failed A:\ComfyUI\custom_nodes\Jovimetrix\core\create_glsl.py cannot import name 'EnumType' from 'enum' (A:\ComfyUI\python\lib\enum.py)
> 
> Works fine under commit [54d61c3](https://github.com/Amorano/Jovimetrix/commit/54d61c37ab8fb6e640162f9ea1bf288c1e8c8db1)

![image](https://github.com/user-attachments/assets/40f6259c-0851-4dd4-b2ae-d5d889364c05)

The commit you reference is several pushes behind. Please make sure to update to the latest.

**Comment by Orenji-Tangerine** [comment]
Yes, what I mean is that when I update it to the latest version, the above error prompts on the console screen during the startup.

**Comment by Amorano** [comment]
What exact version of python comes up in your console?

**Comment by Orenji-Tangerine** [comment]
> What exact version of python comes up in your console?
> 
> https://docs.python.org/3/library/enum.html#enum.EnumType
> 
> Is a standard python library. My first concern is the origin of the error as the create-glsl file doesnt import EnumType itself.
> 
> Also please report the comfy version and the frontend version * (those should be in your log)

My Python is 3.10.11
![image](https://github.com/user-attachments/assets/b83d4f0a-5012-425c-b094-203c9c883156)

I have also uninstalled and reinstalled the node, and it is  the same.

Comfy version from the log file
ComfyUI Version: bc94662b31351ac3ccde903c3829e5abce3d7b6f (2024-09-10 12:43:37)

It should be commit bc94662

**Comment by Orenji-Tangerine** [comment]
![image](https://github.com/user-attachments/assets/f0993eff-d96d-4241-8227-9e11ddecb83b)

**Comment by Orenji-Tangerine** [comment]
It is probably due to Comfy version I am using? But anyway it does not show error with commit: 54d61c3

**Comment by Amorano** [comment]
Your python version is 3.10. 

Even the older versions I made (from 10 months ago) all target python 3.11.

EnumType is a fundamental type that should be in your embedded python (even for 3.10).

I would double check that your comfy is correct and up-to-date.

I will leave this open but I tried various setups today and could not reproduce this behavior.

**Comment by Amorano** [comment]
![image](https://github.com/user-attachments/assets/76b3e35a-5e8e-4707-a8d8-51c0ae690e93)

Some versions to check.

**Comment by Orenji-Tangerine** [comment]
Maybe probably due to using Python 3.10, I could not locate a similar frontend directory.  I am using a ComfyUI launcher from Aki due to ease of updating nodes, so maybe I will stick to the working commit first, in the meantime I will update my launcher environment.

![image](https://github.com/user-attachments/assets/275c753b-b325-4455-bbb7-7ed8fbc321b1)

**Comment by Amorano** [comment]
ok, so if you are using someone else's launcher with their supports, I cant really support that. Sorry, I only support the official comfyui main branch. 

I would try to use the official repository, its not that hard, and will keep you current with everything proper.

**Comment by Orenji-Tangerine** [comment]
Anyway, just to confirm that it only happens on Python 3.10, I have tried using 3.11/3.12 and this issue doesnt happen...

**Comment by Orenji-Tangerine** [comment]
Python 3.10 works again from commit ed67ec5

**Comment by Amorano** [comment]
> Python 3.10 works again from commit [ed67ec5](https://github.com/Amorano/Jovimetrix/commit/ed67ec57c5d38bc5b02ebfd2e7f59c9986c0ccc0)

HA! Yes, you can 100% thank [VykosX](https://github.com/vykosx) for making the convincing argument for a single line change since everything already worked for 310 =D

I would support 310 except I [try to keep to the VFX Platform](https://vfxplatform.com/) as much as I can, but, this seems like a no brainer fix to keep it supported.

Sorry for any time resources wasted!
