### ISSUE TITLE
Could you pls add ComfyUI prefix to your projects?

### ISSUE THREAD

**Issue by pandayummy** [Amorano/Jovimetrix#59]
Jovimetrix  ---- ComfyUI Jovimetrix 

so more people will find it.

**Comment by Amorano** [comment]
no.

**Comment by Amorano** [comment]
That is not going to be a thing. People can find it searching for the things they want to do: Compositing, Midi, etc...

Renaming it now would require a new repository. That is not happening, even in the future. Biggest migration I will do is slipping it inside a sub-folder so it can install like a normal python package.

Sorry!
