### ISSUE TITLE
Keyword Argument Icons seem to be making comfyui error

### ISSUE THREAD

**Issue by Gerkinfeltser** [Amorano/Jovimetrix#6]
Hello again.

Seems ComfyUI don't like the icons used for various setting names.

I get errors like so.
`Error occurred when executing SHAPE GENERATOR (JOV) ✨:

ShapeNode.run() got an unexpected keyword argument '↔️'

  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

![image](https://github.com/Amorano/Jovimetrix/assets/1477787/4e6bbf61-501d-4858-ba91-3346405fa2d1)

**Comment by filliptm** [comment]
bump, me too. Basically all nodes are unusable because of this

**Comment by Amorano** [comment]
Pushing the new branch into main should resolve this issue. The emoji now have full support and have been checked for each node. Please let me know if this is not the case.

**Comment by Gerkinfeltser** [comment]
I'm away for a while, but I'll check it when I get back. Thanks so much!

**Comment by Gerkinfeltser** [comment]
Hey, just getting back now. All seems good (though you already know that)! Thanks for the fix! Sorry for the delayed confirmation!
