### ISSUE TITLE
How to use STREAM READER?

### ISSUE THREAD

**Issue by huameiwei-vc** [Amorano/Jovimetrix#60]
<img width="895" alt="image" src="https://github.com/user-attachments/assets/8db1f07b-4ab6-4c4e-8492-52bd171dd589">
How to capture the window of PS?

**Comment by Amorano** [comment]
You have window selected, but you havent selected a window in the second drop down.

![image](https://github.com/user-attachments/assets/fc103746-1f8b-4d78-b2a1-1fcd770303bb)

You can also get some minor help and links to the example repository if you open the help extension and click any node.

![image](https://github.com/user-attachments/assets/2721403e-c707-4570-a253-d86e7ad2a056)

Let me know if that is working for you.

Cheers

**Comment by huameiwei-vc** [comment]
Hello, Thank you for your response.
I did open the second option, but nothing appeared.
I have reviewed your project and tried opening the help extension, but it shows 502. I am not sure if it is related to my network environment.
But I have already opened the global settings using stash, but it doesn't work.

<img width="928" alt="image" src="https://github.com/user-attachments/assets/db0e623b-561c-4869-a43c-7d5a7f4d6b09">

**Comment by huameiwei-vc** [comment]
Hello, I went to lightning.ai and created another comfyui, tried it and it still doesn't work.

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/6b33bea4-18bf-454e-9237-1be7f36f0b70">

**Comment by Amorano** [comment]
> Hello, Thank you for your response. I did open the second option, but nothing appeared. I have reviewed your project and tried opening the help extension, but it shows 502. I am not sure if it is related to my network environment. But I have already opened the global settings using stash, but it doesn't work.

OS? I only support ComfyUI, not wrappers around ComfyUI, so you would need to yell at whomever is hosting the other package you are using around ComfyUI (pinokio, lighting.ai, etc...)

**Comment by Amorano** [comment]
> Hello, I went to lightning.ai and created another comfyui, tried it and it still doesn't work.
> <img alt="image" width="1229" src="https://private-user-images.githubusercontent.com/125441847/375254129-6b33bea4-18bf-454e-9237-1be7f36f0b70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzA4ODAsIm5iZiI6MTcyODU3MDU4MCwicGF0aCI6Ii8xMjU0NDE4NDcvMzc1MjU0MTI5LTZiMzNiZWE0LTE4YmYtNDU0ZS05MjM3LTFiZTdmMzZmMGI3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNDI5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2VkZTg2NmM0Mzk2YmMwY2VhYTA5ZTViNTNmY2Q0YjJkYTU1ZjI1NmM4ZTRjMWU4MTUzYTQ3MDAzMTljZjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ezYfX_MjtbQdzfQUjRqTVGiVPXrStG3A2Bsq50M4-kI">

That looks like they disallow calls out to the internet as all my help is located in the github:

https://github.com/Amorano/Jovimetrix-examples

**Comment by huameiwei-vc** [comment]
我在 mac 本地建立的 comfyui 也无法使用，网络问题无所谓，主要想使用这个屏幕分享的功能。
<img width="281" alt="image" src="https://github.com/user-attachments/assets/ac92f1c7-e3fb-499b-89cd-7938b4d8ae56">

**Comment by Amorano** [comment]
> 我在 mac 本地建立的 comfyui 也无法使用，网络问题无所谓，主要想使用这个屏幕分享的功能。 <img alt="image" width="281" src="https://private-user-images.githubusercontent.com/125441847/375588637-ac92f1c7-e3fb-499b-89cd-7938b4d8ae56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTA0NzMsIm5iZiI6MTcyODYxMDE3MywicGF0aCI6Ii8xMjU0NDE4NDcvMzc1NTg4NjM3LWFjOTJmMWM3LWUzZmItNDk5Yi04OWNkLTc5MzhiNGQ4YWU1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwMTI5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTQ0OWFhMWFjZWRjMWYxN2E5ZGU3NDE5YjFmOTg2MDg3NDFlOTI3MWRlMmYxZDcxZTE4OWZlNzFhZmU5ZWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-8t_5KnT9c5zNKZcfWCK1KleJmId7WwpY1v7dZMIzFQ">

Sorry, I need to translate that, but I assume you did not understand my previous replies.

If you are using another system, other than commandline comfy, they are probablly blocking your use of SYSTEM DEVICES.

The node is working fine in all Browsers (Opera, Firefox, Chrome, Edge) if you are using a normal comfyui install.

I have *no control* over 3rd party platform providers who wrap comfyui themselves.

**Comment by Amorano** [comment]
And just to be clear, I have no Macs so this will need to be rented -- which wont happen till the weekend.

**Comment by huameiwei-vc** [comment]
Thank you very much

**Comment by Amorano** [comment]
I think I have a working solution. I just pushed it up (version 1.2.43). 

Let me know where it breaks (hopefully it works), as I dont have many robust tools on Mac beyond use.

**Comment by huameiwei-vc** [comment]
An error has occurred,

`[ERROR] An error occurred while retrieving information for the 'WindowCaptureNode' node.
Traceback (most recent call last):
  File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
TypeError: 'dict' object is not callable

[ERROR] An error occurred while retrieving information for the 'WindowCaptureNode' node.
Traceback (most recent call last):
  File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
TypeError: 'dict' object is not callable`

But I can use the full screen one

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/48dd9599-e3a4-46d5-8e78-465d21ce2d83">

**Comment by Amorano** [comment]
> An error has occurred,
> 
> `[ERROR] An error occurred while retrieving information for the 'WindowCaptureNode' node. Traceback (most recent call last): File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 564, in get_object_info out[x] = node_info(x) File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 531, in node_info info['input'] = obj_class.INPUT_TYPES() TypeError: 'dict' object is not callable
> 
> [ERROR] An error occurred while retrieving information for the 'WindowCaptureNode' node. Traceback (most recent call last): File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 564, in get_object_info out[x] = node_info(x) File "/Users/songchao/Documents/comfyui/ComfyUI/server.py", line 531, in node_info info['input'] = obj_class.INPUT_TYPES() TypeError: 'dict' object is not callable`
> 
> But I can use the full screen one


So the only support is for Windows on Mac. Monitor capture is not something I added (Windows only)

**Comment by Amorano** [comment]
Going to assume this is resolved.
