### ISSUE TITLE
Delay node screensaver

### ISSUE THREAD

**Issue by Krishicall** [Amorano/Jovimetrix#61]
Hi, how to disable the screensaver in the delay node? It is incompatible with the browser zoom setting. Ty

**Comment by Amorano** [comment]
Not currently, but I will add an option to enable/disable it.

**Comment by Amorano** [comment]
I just pushed a fix for the zoom issue (should no longer be a problem).

I also added an Enable/Disable for the screensaver, if you don't want to watch the bubbles or are headless.

Cheers for the suggestion! Let me know if that resolves the issue.
