### ISSUE TITLE
Bug with blend node

### ISSUE THREAD

**Issue by NOTlinnkoln** [Amorano/Jovimetrix#62]
blend node generates multiple images 
![image](https://github.com/user-attachments/assets/64f4d858-dc1d-46a1-af44-47cc3c5ab495)

**Comment by NOTlinnkoln** [comment]
problem seems to appear when mask is included

**Comment by NOTlinnkoln** [comment]
or not, continue to investigate 
![image](https://github.com/user-attachments/assets/6cc06eb0-fa25-4939-a535-159ef391cac3)

**Comment by NOTlinnkoln** [comment]
same number 680 appears here 
![image](https://github.com/user-attachments/assets/b1e544eb-9d03-4c1a-8a5a-80bc13fa8aae)
![image](https://github.com/user-attachments/assets/b708eeda-da20-4c8d-affa-78d6f8025f5f)

**Comment by Amorano** [comment]
If mixlab has been fixed, I can try it, but Mixlab breaks the UI in Comfy last I checked (with the beta frontend).

> or not, continue to investigate. seems like WAS load image node is not comparable with blend node ![image](https://private-user-images.githubusercontent.com/179947730/381024744-6cc06eb0-fa25-4939-a535-159ef391cac3.png?

Here you are blending black with black, the result should be black?

**Comment by Amorano** [comment]
> or not, continue to investigate. seems like WAS load image node is not comparable with blend node ![image](https://private-user-images.githubusercontent.com/179947730/381024744-6cc06eb0-fa25-4939-a535-159ef391cac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTIzNzMsIm5iZiI6MTczMDIxMjA3MywicGF0aCI6Ii8xNzk5NDc3MzAvMzgxMDI0NzQ0LTZjYzA2ZWIwLWZhMjUtNDkzOS1hNTM1LTE1OWVmMzkxY2FjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNDI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWJhYzkyM2JiODhiOGY2MWRiNTQ3Y2ZjY2E3ZmViNGI2MTg4NTZkM2VlMWJiZWZhNjE0ZDMyZmQyZmU5MzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sxroQoQrhdGF9WPMazJx_S58MO1NHtIqyqCAgEPMqc8)

![image](https://github.com/user-attachments/assets/4a1ea626-b5f3-45c0-9b9b-4c0e3fe33dfc)

That is the correct result -- black with black == black.

![image](https://github.com/user-attachments/assets/b7472ad2-2e9d-4219-9b5c-f1abd84b0a0b)

when using something other than black on black, it works correctly.

**Comment by NOTlinnkoln** [comment]
Nah, black layers just for checking if things work. Main goal is to compose .png layers 2000x680 size.

**Comment by Amorano** [comment]
> problem seems to appear when mask is included ![image](https://private-user-images.githubusercontent.com/179947730/381024902-dc496b91-f84b-474f-adff-db9393a32758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTIzNzMsIm5iZiI6MTczMDIxMjA3MywicGF0aCI6Ii8xNzk5NDc3MzAvMzgxMDI0OTAyLWRjNDk2YjkxLWY4NGItNDc0Zi1hZGZmLWRiOTM5M2EzMjc1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNDI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzEwNTI2OTliNGNiNjY3NTExYTRkMGUyMjc3MTQ0ZDY0OGNjZDUzZjc0ZTNhMzdhNGU0NTEzM2EzODVjNjEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YdNRAQzUfM-2qCDViKf_X-yePKih-XxvrXNj_nJxYN8)

I would need to see if you have multiple masks. My nodes will auto-batch when they are given a batch, in any input. I assume the mask has multiple outputs? Cant see the workflow that makes it.

**Comment by NOTlinnkoln** [comment]
i will prepare workflow for you to test things yourself

**Comment by Amorano** [comment]
> same number 680 appears here ![image](https://private-user-images.githubusercontent.com/179947730/381029292-b1e544eb-9d03-4c1a-8a5a-80bc13fa8aae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTIzNzMsIm5iZiI6MTczMDIxMjA3MywicGF0aCI6Ii8xNzk5NDc3MzAvMzgxMDI5MjkyLWIxZTU0NGViLTlkMDMtNGMxYS04YTVhLTgwYmMxM2ZhOGFhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNDI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTNjMTU3ZjM4ZmQyYzA3Yjc1M2EyZDJmM2NkYzY1ZGNlNmI5MTA5NzgwZmEwZDZlZGM4NTRjMzUzZjVhYTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._jJ3cO0Ow5fyEkEwA7d2k8d3z-BVvjUli01I6Jkyqc0) ![image](https://private-user-images.githubusercontent.com/179947730/381029520-b708eeda-da20-4c8d-affa-78d6f8025f5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTIzNzMsIm5iZiI6MTczMDIxMjA3MywicGF0aCI6Ii8xNzk5NDc3MzAvMzgxMDI5NTIwLWI3MDhlZWRhLWRhMjAtNGM4ZC1hZmZhLTc4ZDZmODAyNWY1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNDI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjE5NjQ5MjNlZDkxYWM4MmZjNWM4OTdiYmM0NTgwNTA4ODZkNTVmZTNhODYyNDQ2MDM2YzkwZWVkNzkzNWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jBvLYwvU0mbHlAuc-jugHyocPdlFR5Z0QBrVrZY1Iqo)

And this one is because Mixlabs outputs a batch of layers (the 9 dot output). You "can" stuff anything into my inputs because they will accept most anything and try to translate it into the proper input, but I dont not have an auto-translation for mixlab's multiple layer outputs. Most likely it is trying to strip off each layer and treat it as an image, which is causing the tensor problem.

**Comment by Amorano** [comment]
> blend node generates multiple images ![image](https://private-user-images.githubusercontent.com/179947730/381019609-64f4d858-dc1d-46a1-af44-47cc3c5ab495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTMzMDcsIm5iZiI6MTczMDIxMzAwNywicGF0aCI6Ii8xNzk5NDc3MzAvMzgxMDE5NjA5LTY0ZjRkODU4LWRjMWQtNDZhMS1hZjQ0LTQ3Y2MzYzVhYjQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNDQzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWJjZmQxYmIwOTIxN2M4MGJkODM2MjA1NWIzNjk1YmE2OWQ1YjFhZTY0OWM1YzY2NjFlYWU0NGQ0NTczMzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7sTQOhFO3mwE9oZy_qcwvGYyLKVJQkdam0gv_iJ-uJ0)

Here I would also need to see how you made the image(s) prior to the blend as well. I cannot tell what your inputs are, so I cannot tell you if it is working as intended.

**Comment by NOTlinnkoln** [comment]
![background](https://github.com/user-attachments/assets/269f9fb2-9420-4759-91b9-565709c7159c)
![color](https://github.com/user-attachments/assets/a799ec1f-d8f8-4219-941c-86f4ce004c3b)
[composeImages_v1_toJOV.json](https://github.com/user-attachments/files/17558762/composeImages_v1_toJOV.json)
![floor](https://github.com/user-attachments/assets/469cb439-0c3f-4ba5-82fc-a38a1a84730e)
![pattern](https://github.com/user-attachments/assets/dbb135ab-c297-41e0-88fb-cc2f65281fb7)

**Comment by NOTlinnkoln** [comment]
tried to add files with proper naming but didn't figure it out so
![image](https://github.com/user-attachments/assets/ac91f190-c433-4458-8b7f-04b41943816d)

**Comment by NOTlinnkoln** [comment]
![image](https://github.com/user-attachments/assets/289cffee-43fc-4d75-9eb8-7f56d25811

**Comment by Amorano** [comment]
> ![image](https://private-user-images.githubusercontent.com/179947730/381181007-444a1ac2-d498-401d-b702-0ac01db52351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTQyMzgsIm5iZiI6MTczMDIxMzkzOCwicGF0aCI6Ii8xNzk5NDc3MzAvMzgxMTgxMDA3LTQ0NGExYWMyLWQ0OTgtNDAxZC1iNzAyLTBhYzAxZGI1MjM1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNDU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGNhMzRiYjYyMWY4ZjRkYzkyNGY0OGU3M2Y5OGUwZjM3MzFmYWIwYjBlYzZkOTlmMTc5YzFiZmFlZTY1MWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j8i40MInjmVnjtZaJwo4aubnFT2ozyHLZGm5iLzssLY)

No worries. I can reconstruct. Just an FYI, the shape image is half the height of the other inputs (349 vs 680). I assume you want it stretched across the final output resoulution (2100x680)

**Comment by NOTlinnkoln** [comment]
Oh, my bad. Send you wrong image. All the images should be 2100x680. For test case i don't mind if its stretches

**Comment by Amorano** [comment]
and I just want to check that the background image you sent is correct? Because that looks like what you want as a final output?

**Comment by NOTlinnkoln** [comment]
Not really, background.png just reference image that i use to compete with results of workflow

**Comment by Amorano** [comment]
> Not really, background.png just reference image that i use to compete with results of workflow

that is what I said. =D I dont have your other image to "blend". You did not post the stone in the center bottom of the final

**Comment by Amorano** [comment]
![image](https://github.com/user-attachments/assets/3a228386-81b6-4835-8fca-f88577139718)

Given what I had, this is the blend of those images. The gradient used/sent is (inverted in the blend) working as it should for the gradient it is. If you want the circular focus on the bottom-center then you should make one more appropriate to that comp op.

**Comment by NOTlinnkoln** [comment]
with "load image" it works for me too. But with "image loader" by was it doesn't work for some reasons

**Comment by Amorano** [comment]
I don't really use load image, I use my Queue or Queue Too nodes since they fully load RGBA and I don't need to invert and add back the mask as an alpha. I just did not want to confuse the example. =D

I will assume (since I no longer use WAS) that his are not loading the A channel or manipulating it differently.

**Comment by NOTlinnkoln** [comment]
Oh gosh, this nodes straight up fire!!!
WAS loading RGBA images, but i guess yeah, maintaining it differently. fells like combination of your node with WAS has some data misunderstanding where width of WAS image recognized as batch in your node.

**Comment by NOTlinnkoln** [comment]
Thank you, a lot, for help!
