### ISSUE TITLE
Conflicting Pillow version when installing requirements.txt

### ISSUE THREAD

**Issue by Colt1052** [Amorano/Jovimetrix#67]
I'm sure you're on it since this is so recent, but the recent changes made installing dependencies from requirements.txt fail.  The culprit is below.

The conflict is caused by:
     The user requested Pillow>=11.0.0
     blendmodes 2024.1.1 depends on Pillow<11 and >=10.2.0

**Comment by Amorano** [comment]
> I'm sure you're on it since this is so recent, but the recent changes made installing dependencies from requirements.txt fail. The culprit is below.
> 
> The conflict is caused by: The user requested Pillow>=11.0.0 blendmodes 2024.1.1 depends on Pillow<11 and >=10.2.0

Are you using something other than Windows?

On my windows boxes, across multiple systems, I am using Pillow 11.0.0 and blendmodes 2024.1.1

**Comment by Amorano** [comment]
![image](https://github.com/user-attachments/assets/f94d4731-7453-408a-bce0-618e6d739a51)

I will be pushing this in short order, but, please take note of the requirements.

Let me know if dropping the Pillow requirement works

HTH
