### ISSUE TITLE
Color Calibration button prevents settings from being opened. 

### ISSUE THREAD

**Issue by Xenodimensional** [Amorano/Jovimetrix#7]
Windows 10. Edge.

No matter where I click I cannot open the settings dialog box, the Color Calibration dialog opens instead. 

In Firefox the palette icon is on the left side of the Queue window and the settings can be opened. In Edge the palette icon appears randomly along the top row and seems to obscure the feed and setting buttons. 

![image](https://github.com/Amorano/Jovimetrix/assets/66627464/f3370050-5700-47a8-a29f-c06925edcc98)

**Comment by Amorano** [comment]
TY for the report. I will endeavor to fire up edge and make a specific CSS to resolve.

**Comment by Amorano** [comment]
![image](https://github.com/Amorano/Jovimetrix/assets/225178/293a6f46-3d8a-4f9b-916c-4219f3495cc7)

I have tried to replicate this issue, however, I am unable. The icon appears in the proper location. I have quite a few libraries loaded, so I tried both with and without them.

I suggest you remove any extra libraries you have (to a temp folder first) and see if the icon moves. That could help narrow down finding which library could be affecting the style.

**Comment by Xenodimensional** [comment]
It turned out I wasn't given XXX.91 in my latest system update and after manually updating from XXX.61 to XXX.91 it is working again. I'll check versions next time I encounter anything weird. Thank you for your assistance, it's very appreciated!! 

I love the pigment preferences, not just for colouring nodes but for being able to see the list of installed nodes in their categories.  

P.S. are NDI or Spout nodes planned or a possibility?

**Comment by Amorano** [comment]
> It turned out I wasn't given XXX.91 in my latest system update and after manually updating from 

No worries. I should continue to check all the browsers per update in either case! Thank you for checking.

> P.S. are NDI or Spout nodes planned or a possibility?

I will most likely add OSC support; however, someone already made an excellent NDI support for Comfy:

https://github.com/ningxiaoxiao/comfyui-NDI

HTH!
